import imp, os, re, sys, config, importlib

'''
Class that contains two parts:
    - replacement of tags with tags + persistant data as specified in config file
    - regex replacement for <?wsgi ?> method calls in html for dynamic content
'''

class Html():
    structure = {}
    
    def __init(self):
        self.structure['html']  = config.TEMPLATES.get("html", None)
        self.structure['/html'] = config.TEMPLATES.get("/html", None)
        self.structure['head']  = config.TEMPLATES.get("head", None)
        self.structure['/head'] = config.TEMPLATES.get("/head", None)
        self.structure['body']  = config.TEMPLATES.get("body", None)
        self.structure['/body'] = config.TEMPLATES.get("/body", None)

    def __str__(self):
        return "{}\n{}\n{}\n{}\n{}\n{}\n".format(
            *structure.values())

    def parse(self, htmlfile=None):
        '''
        :Description:
            Replaces the incoming htmlfile's tags with those
            in the Template, or none at all.
            
            Tags that can be Templated are limited to html, body and head.
            If you want autogenerated code beyond that, Template wsgi tags.
            
            Templates are not recommended on pages where the main tags:
                - html
                - body
                - head
            are manipulated because we can either replace ALL instances of
            <tag> with the Template, or the first instance. Even if comments
            are stripped out that may contain the strings, jQuery may require
            <tag> references (or at least javascript), so this method is
            dangerous. The *correct* solution to using templates is to not
            use any input files whatsoever. In fact, if parse() detects
            a None input file, it will auto generate to the best of its ability,
            a functioning html file even if it ends up blank.
            
            Because Templates are created first, then wsgi tags are parsed,
            a template can reference a python method so absolutely NO
            html file is required for wsgi to run properly.
            Cool trick eh?
            
        :Parameters:
            - htmlfile: string; path to the file to read and replace
              tags with
              
        :Returns:
            - string; output of replaced input file with corrections made
        '''
        templatedhtml = []
        # Must append in order
        if not htmlfile is None:
            # we have a string to replace
            templatedhtml = open(htmlfile, 'r').read()
            for key in self.structure.keys():
                if not self.structure.get(key) is None:
                    templatedhtml.replace(key, 
                                          self.structure[key])
                
        else:
            for x in ['html', 'head', '/head', 'body', '/body', '/html']:
                if self.structure.get(x) is None:
                    templatedhtml.append('<{}>'.format(x))
                else:
                    templatedhtml.append(self.structure[x])
        return templatedhtml
           
def __replace_tag(html_contents, wsgi_string, wsgi_result):
    """
    :Description:
        Replaces the wsgi tag with the wsgi result.
        This method does not actually *call* the wsgi method, nor
        ensure that the module and class and arguments are parsed.
        It's a simple "go through html file and replace tags with
        result".
        
    :Parameters:
        - html_contents: string; entire html file
        - wsgi_string: the tag complete with module, class and args
        - wsgi_result: the returned value(s) of the method call
    """
    return re.sub(r'''{}'''.format(wsgi_string),
                     str(wsgi_result), html_contents)

def __call_wsgi(*cmd_tuple):
    """
    :Description:
        Calls and returns the python command specified by wsgi, does NOT 
        convert it to a string format.
        Arguments for methods are ALWAYS in a string.
        
        DANGER:
            You may need to parse the string if you are expecting a list or tuple or 
            dictionary. You *may* have to use eval, but it is DANGEROUS!
        
    :Parameters:
        - cmd_tuple: tuple or list in format (module, (...), args,) where the 
          (...) refers to a tuple where one or more strings can be specified;
          a minimum of a method call must be specified (without ending ()'s )
          that is lead up by zero-or-more python components (such as classes).
          :example:
              (<module datetime>, ('datetime', 'now',)) -> current datetime
          Please note that wsgi is meant for calling module-level methods,
          not class methods, although it should be possible by specifying
          using period delimited module paths in <wsgi ?> tags.
            
    :Returns:
        Result of python method call
    """
    # Check for "." in the module path: If found, this is a customized
    # module that we import using full absolute path; otherwise we
    # attempt a simple __import__ on that module, which works for official
    # imports and modules on the sys.path (customs won't be)
    
    cmd_tuple = tuple([x for x in cmd_tuple if bool(x)])
#    if mod == None:
#        raise Exception("Error: WSGI Module Import invalid; Got 'NoneType'")
    modpath = cmd_tuple[0].split('.')
    if len(modpath) > 1:
        # Parse period-separated string into list, module import name should be
        # in last position, import path is rest of array
        tuple_sep = len(modpath) - 1
        mod = importlib.import_module(modpath[tuple_sep], modpath[:tuple_sep])
    else:
        mod     = importlib.import_module(modpath[0])
    classes = cmd_tuple[1]
    method  = cmd_tuple[2]
    try:
        args = cmd_tuple[3:]
    except:
        pass
    # Arguments parsed here:
    funcbuild = getattr(mod, cmd_tuple[1])
    funcbuild = getattr(funcbuild, cmd_tuple[2])
    retval = funcbuild
    if len(cmd_tuple) > 3: # (mod, method, func)
        return funcbuild(*cmd_tuple[:3])
    return retval()

def parse_wsgi_tags(html_contents):
    """
    :Description:
        Find all wsgi tags found in the html body and for each instance,
        call a method to determine the python values of the method call,
        then replace the results of the method call with the tag for the
        html body.
        
        Each step is done in a different method. Actual replacement is done
        here.

        Calls __call_wsgi to return string results of method call, then
        __replace_tags to switch <?wsgi ?> with "results" in the html 
        code
        
    :Parameters:
        - html_contents: string of the entire html file
        
    :Returns:
        String of html contents with replaced wsgi tags and results.
    """
    for wsgi in re.findall('<\?wsgi(.*)\?>', html_contents):
        return __call_wsgi(*wsgi.split(' '))
        #return str([line for line in wsgi if line!= ''])
    #html_contents = self.__replace_tag(html_contents, wsgi, __call_wsgi(wsgi))
    #tmp += '{}\n'.format(str(wsgi))
        # Place arguments in a string, not as a list
        #            passin = (mod, classes, args, kwargs)
#            result = __call_wsgi(passin)
#            html_contents = __replace_tag(html_contents, pystring, result)
    return str(tmp)
